[tool.black]
line-length = 120
skip-string-normalization = false

[tool.isort]
py_version = 311
profile = "black"
extend_skip_glob = []
skip_gitignore = true
line_length = 120
src_paths = ["src"]
atomic = true
